version: "3.8"

services:
  postgres:
    image: postgres:13
    restart: always
    environment: POSTGRES_USER:user
      POSTGRES_PASSWORD:password
      POSTGRES_DB:mydb
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib.postgresql/data
